### ISSUE TITLE
No such file or directory: 'onlyTopicsData.json'

### ISSUE THREAD

**Issue by robertli9786** [peteroh23/KnowBot#1]
Hi, When i downloaded and ran your code, it popped up:

"No such file or directory: 'onlyTopicsData.json'  "

Is there a file missing or how to solve it? Many thanks.

**Comment by peteroh23** [comment]
I just uploaded a zip files that has 'onlyTopicsData.json'. You will have to unzip it first, before you can use it for the ChatBot. Thanks for letting me know the issue!
